project:
  type: book
  output-dir: docs
  resources: 
    - "images/*"

number-depth: 2

book:
  title: "STAT 451: Causal Inference"
  subtitle: "Fall 2026 Course Notes"
  favicon: "images/451_favicon.png"
  page-footer:
    left: |
      Copyright 2026 Leslie Myint, CC BY-NC-SA 4.0
  sidebar:
    collapse-level: 2
    pinned: true
    search: true
    style: "docked"
    border: true
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Course Logistics"
      chapters: 
        - icon: calendar3
          href: logistics/schedule.qmd
        # - icon: list-check
        #   href: logistics/learning-objectives.qmd
        - icon: asterisk
          href: logistics/syllabus.qmd
        - icon: brush-fill
          href: logistics/project.qmd
    - part: "Foundational Ideas"
      chapters:
        - icon: database-fill-gear
          href: activities/01-foundations.qmd
    - part: "Causal Graphs"
      chapters:
        - icon: bezier2
          href: activities/02-causal-graphs-intro.qmd
        - icon: gear-fill
          href: activities/03-causal-graphs-simulation.qmd
        # - icon: search
        #   href: activities/04-causal-graphs-identification.qmd
    - part: "Assignments"
      chapters:
        - hw/assignment1.qmd
        - hw/assignment2.qmd
  appendices:
    - appendices/stat155.qmd
    - appendices/r_rstudio.qmd
    - appendices/r_resources.qmd

format:
  html:
    theme:
      light: [yeti, smaller_lists.scss]
      dark: [solar, smaller_lists.scss]
    mainfont: ubuntu, sans-serif
    css: styles.css
    execute:
      echo: true
      code-fold: true
      cache: false
